### ISSUE TITLE
PDFs don't render at "/patients/[patient id]/health_card.pdf"

### ISSUE THREAD

**Issue by gjskha** [dvci/health_cards#89]
PDFs don't render when fetching the PDF at the route "/patients/[number]/health_card.pdf" where [number] is the patient's ID. I found this message in the logs:

```
ActionView::Template::Error (The asset "qr-code.js" is not present in the asset pipeline.
):
1: <%= javascript_pack_tag 'qrcode' %>
2: <%= wicked_pdf_javascript_include_tag "qr-code" %>
3:
4: <%=wicked_pdf_stylesheet_link_tag 'pdf' %>
5: <p id="notice"><%= notice %></p>

app/views/health_cards/show.pdf.erb:2
app/controllers/health_cards_controller.rb:21:in `block (2 levels) in show'
app/controllers/health_cards_controller.rb:12:in `show'
app/controllers/application_controller.rb:31:in `handle_fhir_errors'
```

I noticed that there is a file at "app/javascript/packs/qrcode.js" so I changed  the erb at line 2 above from ```qr-code``` to ```qrcode``` but it doesn't make a difference -- looks like it could be doing some fancy caching somewhere.

**Comment by ssayer** [comment]
PR #88 should address this, as it finalizes our migration from JS based QR code generation to server side.

**Comment by radamson** [comment]
@gjskha can you update to the latest `main` branch and see if the recent merge of #88 has fixed your issue? I'm able to get the PDF to render on main locally and in docker.

If you are using docker you'll need to set the host appropriately (e.g. `docker run -p 3000:3000 --env HOST=http://localhost:3000 health_cards`)

**Comment by gjskha** [comment]
I can indeed generate PDFs now, using non-Docker method.  Closing.
